version: "3.9"

services:
  app:
    container_name: recette-api
    build:
      context: . # Construit l'image à partir du Dockerfile dans le répertoire actuel
    depends_on:
      db:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: harouna
      DB_NAME: gestion_recette
    ports:
      - "3010:3010"
    networks:
      - default

  db:
    container_name: gestion-recette
    image: mysql:8
    environment:
      MYSQL_DATABASE: gestion_recette
      MYSQL_ROOT_PASSWORD: harouna
    ports:
      - "3307:3306"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - default

volumes:
  db-config:
  db-data:

networks:
  default:
