
services:
  app:
    container_name: recette-api
    build:
      context: . # Construit l'image à partir du Dockerfile dans le répertoire actuel
    depends_on:
      db:
        condition: service_started
    environment:
      DB_HOST: ${HOST}
      DB_USER: ${USE}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: gestion_recette
    ports:
      - "3308:3005"
    networks:
      - default

  db:
    container_name: gestion-recette
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - default

volumes:
  db-config:
  db-data:

networks:
  default:
