services:
  app:
    container_name: recette-api
    image: recette
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/index
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
